const Components = {
  Alert: require('./Components/Alert'),
  AlertHeader: require('./Components/Alert/AlertHeader'),
  Button: require('./Components/Button'),
  ButtonGroup: require('./Components/Button/ButtonGroup'),
  Column: require('./Components/Column'),
  Form: require('./Components/Form'),
  Field: require('./Components/Form/Field'),
  Fieldset: require('./Components/Form/Fieldset'),
  Message: require('./Components/Form/Message'),
  Grid: require('./Components/Grid'),
  Unit: require('./Components/Grid/Unit'),
  Link: require('./Components/Link'),
  List: require('./Components/List'),
  ListItem: require('./Components/List/Item'),
  Loader: require('./Components/Loader'),
  Menu: require('./Components/Menu'),
  MenuHeading: require('./Components/Menu/MenuHeading'),
  MenuItem: require('./Components/Menu/MenuItem'),
  MenuLink: require('./Components/Menu/MenuLink'),
  MenuList: require('./Components/Menu/MenuList'),
  Table: require('./Components/Table'),
  TableBody: require('./Components/Table/TableBody'),
  TableCaption: require('./Components/Table/TableCaption'),
  TableCell: require('./Components/Table/TableCell'),
  TableHead: require('./Components/Table/TableHead'),
  TableRow: require('./Components/Table/TableRow'),
  Tag: require('./Components/Tag'),
  Tile: require('./Components/Tile'),
  Table: require('./Components/Table')
};

export default Components;
